*Generated by GrADS Color Maker



 'set rgb 22 255 255 255'
 'set rgb 23 135 206 255'
 'set rgb 24 0 191 255'
 'set rgb 25 255 255 0'
 'set rgb 26 255 165 0'
 'set rgb 27 255 0 0'
 'set rgb 28 150 0 0'

'set rbcols 22 23 24 25 26 27 28 '
return
